### PR TITLE
add hex support

### PR DESCRIPTION
**Pull request by tomijaga**

### CODE REVIEW

**Review by ByronBecker — APPROVED** [review]
Thanks for this contribution and fixing the README! Merging in

**Comment by ByronBecker** [comment]
@tomijaga tagged with release version `v1.1.0` - https://github.com/ByronBecker/motoko-color/releases/tag/v1.1.0

**Comment by ByronBecker** [comment]
Also, regarding your comment on error handling I think the ignore if error case is fine for now. You could have it print out a `Debug.print("The provided hexCode " # hexCode # " is invalid");`, but I think this is good for now - it sort of follows how in CSS colors don't apply if the hex string is invalid

**Comment by tomijaga** [comment]
> Also, regarding your comment on error handling I think the ignore if error case is fine for now. You could have it print out a Debug.print("The provided hexCode " # hexCode # " is invalid");, but I think this is good for now - it sort of follows how in CSS colors don't apply if the hex string is invalid

Okay, good to know that I could have done that. My initial thought was to log to the terminal, but I wasn't sure if it would be appropriate to log the errors in production. 

> Thanks for this contribution and fixing the README! Merging in

Awesome! Thanks again for the review and merge.

**Pull request merged**
